version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - pip install awscli --upgrade --user
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=518573545843.dkr.ecr.ap-south-1.amazonaws.com/user-ms
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - apt-get update
      - apt-get install sshpass
  build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - echo $REPOSITORY_URI
      - echo $IMAGE_TAG
      # - aws s3 cp s3://linkme-notification-service-us-east-1-codepipeline/.env .
      - aws s3 cp s3://codepipeline-ap-south-1-553528238017
      - docker build --rm -f Dockerfile -t nikhil-backend:latest.
      - docker tag nikhil-backend:latest $REPOSITORY_URI:latest
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Writing image definitions file...
      - sshpass -p "Start@101" ssh -o StrictHostKeyChecking=no ubuntu@172.17.0.1 bash  usermsDocker.sh
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:latest > imageDetail.json
      - cat imageDetail.json
artifacts:
  files:
    - imageDetail.json